# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        db_users:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: app_security_login
                check_path: app_security_check
                #csrf_provider: security.csrf.token_manager
            logout:
                path: app_security_logout
                target: /

    access_control:
#        - { path: ^/update, roles: ROLE_ADMIN  }
#        - { path: ^/remove, roles: ROLE_ADMIN  }